---
- hosts: localhost
  connection: local
  vars:
    ssh_key: k8s
    k8s_version: v1.8.1
    k8s_num_nodes: 2
    k8s_security_group_name: k8s
    k8s_node_prefix: k8s
    cs_api_url: "{{ cs_api_url }}"
    cs_api_key: "{{ cs_api_key }}"
    cs_api_secret: "{{ cs_api_secret }}"
    cs_ssl_verify: false
  roles:
    - common
    - k8s
