- name: Create Folder
  file:
    path: certificates
    mode: 0755
    state: directory

- stat:
    path: certificates/server.crt
  register: st

- name: Create master-openssl.cnf
  template:
    dest: certificates/master-openssl.cnf
    src: ../templates/master-openssl.cnf.j2

- name: Create worker-openssl.cnf
  template:
    dest: certificates/worker-openssl.cnf
    src: ../templates/worker-openssl.cnf.j2

- name: Create the certificates for the kubernetes deployement
  shell: |
        openssl genrsa -out certificates/ca.key 2048
        openssl req -x509 -new -nodes -key certificates/ca.key -subj "/CN={{k8s_external_ip}}" -days 10000 -out certificates/ca.crt

        openssl genrsa -out certificates/server.key 2048
        openssl req -new -key certificates/server.key -subj "/CN={{k8s_external_ip}}" -out certificates/server.csr -config certificates/master-openssl.cnf

        openssl x509 -req -in certificates/server.csr -CA certificates/ca.crt -CAkey certificates/ca.key -CAcreateserial -out certificates/server.crt -days 10000 -extensions v3_req -extfile certificates/master-openssl.cnf
        openssl x509  -noout -text -in certificates/server.crt

        openssl genrsa -out certificates/service-accounts.key 2048
        openssl req -new -key certificates/service-accounts.key -subj "/CN={{k8s_external_ip}}" -out certificates/service-accounts.csr -config certificates/master-openssl.cnf

        openssl x509 -req -in certificates/service-accounts.csr -CA certificates/ca.crt -CAkey certificates/ca.key -CAcreateserial -out certificates/service-accounts.crt -days 10000 -extensions v3_req -extfile certificates/master-openssl.cnf
        openssl x509  -noout -text -in certificates/server.crt
  args:
        executable: /bin/bash
  delegate_to: localhost
  when: not st.stat.exists

- name: Create worker certificates for the kubernetes deployment
  shell: |
        openssl genrsa -out certificates/{{ k8s_node_prefix }}-node-{{ item }}.key 2048
        WORKER_FQDN={{ k8s_node_prefix }}-node-{{ item }} openssl req -new -key certificates/{{ k8s_node_prefix }}-node-{{ item }}.key -subj "/CN={{ k8s_node_prefix }}-node-{{ item }}" -out certificates/{{ k8s_node_prefix }}-node-{{ item }}.csr -config certificates/worker-openssl.cnf
        WORKER_FQDN={{ k8s_node_prefix }}-node-{{ item }} openssl x509 -req -in certificates/{{ k8s_node_prefix }}-node-{{ item }}.csr -CA certificates/ca.crt -CAkey certificates/ca.key -CAcreateserial -out certificates/{{ k8s_node_prefix }}-node-{{ item }}.crt -days 10000 -extensions v3_req -extfile certificates/worker-openssl.cnf
        openssl x509  -noout -text -in certificates/{{ k8s_node_prefix }}-node-{{ item }}.crt
  args:
        executable: /bin/bash
  delegate_to: localhost
  with_sequence: count={{ k8s_num_nodes }}
  when: not st.stat.exists
